
# Setup
title:               GND123
tagline:             'A Jekyll theme'
description:         GND blog
url:                 https://gnd123.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              GND
  url:               https://gnd123.github.io/
  email:             wldn0202@gmail.com

# Custom vars
version:             1.0.0
