
# Setup
title:               GND123
tagline:             'A GND Blog'
description:         GND blog
url:                 https://localhost:4000/
#url:                 https://gnd123.github.io/
baseurl:             ''
paginate:            5
plugins: [jekyll-paginate]

# About/contact
author:
  name:              GND
  url:               https://gnd123.github.io/
  email:             wldn0202@gmail.com

# Custom vars
version:             1.0.1
